-- Phạm Nguyễn 2001210784
-- Nhân viên
USE DB_QLNHANVIEN
----
SELECT * FROM NHANVIEN, PHANCONG
WHERE NHANVIEN.MANV = PHANCONG.MANV
-- 
SELECT * FROM NHANVIEN JOIN PHANCONG
ON NHANVIEN.MANV = PHANCONG.MANV

--CÁCH 2  HIỂN THỊ LẠI NHỮNG NHÂN VIÊN CHƯA ĐƯỢC PHÂN CÔNG 
SELECT * FROM NHANVIEN LEFT JOIN PHANCONG
ON NHANVIEN.MANV = PHANCONG.MANV
WHERE MADA IS NULL

-- CÁCH 2: 
SELECT * 
FROM NHANVIEN
WHERE MANV NOT IN (
  SELECT MANV 
  FROM PHANCONG
  ) 

SELECT NHANVIEN.* 
FROM NHANVIEN
WHERE NOT EXISTS (SELECT * 
  FROM PHANCONG 
  WHERE PHANCONG.MANV = NHANVIEN.MANV)

-- Sinh viên
USE DB_QLSINHVIEN


SELECT *
FROM DIEM

SELECT *
FROM SINHVIEN
-- 
SELECT *
FROM KHOA

SELECT *
FROM THANNHAN
-- 
SELECT *
FROM QUANHE

SELECT *
FROM GIANGVIEN



SELECT *
FROM LOP

SELECT *
FROM DSSV_LOP

SELECT *
FROM GIANGDAY


SELECT *
FROM MONHOC

-- câu1
UPDATE SINHVIEN
SET DCHI = N'CẦN THƠ'
WHERE MASV = 'SV002';

-- câu 2
SELECT MASV, HOTEN
FROM SINHVIEN

-- câu 3
SELECT MASV, HOTEN
FROM SINHVIEN
WHERE SINHVIEN.DCHI = N'Vũng Tàu';

-- câu 4

SELECT SOTC
FROM MONHOC
WHERE TENMH = N'Toán rời rạc';

-- câu 5 
SELECT * 
FROM LOP
WHERE MAKH IN (SELECT MAKH 
FROM KHOA WHERE MAKH = 'TH')

-- 5.1
SELECT LOP.* 
FROM LOP,KHOA
WHERE LOP.MAKH = KHOA.MAKH

-- 5.2
SELECT LOP.* 
FROM LOP
WHERE EXISTS (SELECT * 
  FROM KHOA 
  WHERE LOP.MAKH = KHOA.MAKH AND (KHOA.MAKH = 'TH'))

--  5.3
SELECT LOP.* 
FROM (SELECT * 
      FROM KHOA 
      WHERE KHOA.MAKH = 'TH') AS KHOA, LOP
WHERE LOP.MAKH = KHOA.MAKH

-- Câu 6
SELECT MASV, HOTEN
FROM SINHVIEN
WHERE HOTEN LIKE N'Nguyễn%'

-- câu 7.1
SELECT MASV, HOTEN, NSINH, DCHI
FROM SINHVIEN, LOP
WHERE SINHVIEN.MALOP = LOP.MALOP AND LOP.MALOP ='10DHTH1';

-- câu 7.1
SELECT MASV, HOTEN, NSINH, DCHI
FROM SINHVIEN
WHERE MALOP IN (
              SELECT MALOP 
              FROM LOP 
              WHERE MALOP = '10DHTH1')

-- câu 7.2
SELECT  MASV, HOTEN, NSINH, DCHI
FROM SINHVIEN
WHERE EXISTS (
              SELECT MALOP 
              FROM LOP 
              WHERE SINHVIEN.MALOP = LOP.MALOP 
                      AND LOP.MALOP ='10DHTH1')

-- câu 7.3
SELECT  MASV, HOTEN, NSINH, DCHI
FROM SINHVIEN , (SELECT MALOP 
              FROM LOP 
              WHERE MALOP ='10DHTH1') AS LOP
WHERE LOP.MALOP = SINHVIEN.MALOP

-- câu 8
SELECT * 
FROM MONHOC
WHERE SOTC = 1 OR SOTC = 2;

-- CÂU 9
SELECT SINHVIEN.MASV, HOTEN, TENMH, LANTHI, DIEMTHI
FROM SINHVIEN
JOIN DIEM ON SINHVIEN.MASV = DIEM.MASV
JOIN MONHOC ON DIEM.MAMH = MONHOC.MAMH
WHERE DIEM.LANTHI = (
                  SELECT MAX(LANTHI) 
                  FROM DIEM
                  WHERE MAMH = MONHOC.MAMH AND MASV = SINHVIEN.MASV)

-- CÂU 10 
SELECT HOTEN, DCHI
FROM SINHVIEN, LOP
WHERE GTINH = N'Nữ' AND MAKH = 'TH'

-- CÂU 10 
SELECT HOTEN, DCHI
FROM SINHVIEN
WHERE GTINH = N'Nữ' AND (DCHI = N'TP HCM' OR DCHI = N'Vũng Tàu')

-- CÂU 11
SELECT SINHVIEN.MASV, HOTEN, DIEMTHI
FROM SINHVIEN, DIEM
WHERE MALOP = '10DHTH1' AND (DIEM.DIEMTHI >= 6 AND DIEM.DIEMTHI <=8)


-- Tính điểm trung bình của từng sinh viên cho biết 
-- sinh viên có điểm trung bình cao nhất msv họ tên điểm trung bình
-- CÂU 9
SELECT SINHVIEN.MASV, HOTEN, TENMH, LANTHI, DIEMTHI
FROM SINHVIEN
JOIN DIEM ON SINHVIEN.MASV = DIEM.MASV
JOIN MONHOC ON DIEM.MAMH = MONHOC.MAMH
WHERE DIEM.LANTHI = (
                  SELECT MAX(LANTHI) 
                  FROM DIEM
                  WHERE MAMH = MONHOC.MAMH AND MASV = SINHVIEN.MASV)

SELECT SINHVIEN.MASV, HOTEN,  AVG(DIEMTHI) AS 'DIEM TB'
FROM SINHVIEN ,DIEM, MONHOC
WHERE SINHVIEN.MASV = DIEM.MASV 
      AND DIEM.MAMH = MONHOC.MAMH 
      AND DIEM.LANTHI = (
                  SELECT MAX(LANTHI) 
                  FROM DIEM
                  WHERE MAMH = MONHOC.MAMH AND MASV = SINHVIEN.MASV)
GROUP BY SINHVIEN.MASV;


SELECT SINHVIEN.MASV, SINHVIEN.HOTEN, AVG(DIEM.DIEMTHI) AS DIEM_TRUNG_BINH
FROM SINHVIEN
JOIN DIEM ON SINHVIEN.MASV = DIEM.MASV
JOIN MONHOC ON DIEM.MAMH = MONHOC.MAMH
WHERE DIEM.LANTHI = (SELECT MAX(LANTHI) 
                    FROM DIEM
                    WHERE MAMH = MONHOC.MAMH AND MASV = SINHVIEN.MASV)
GROUP BY SINHVIEN.MASV, SINHVIEN.HOTEN


SELECT SINHVIEN.MASV, SINHVIEN.HOTEN, AVG(DIEM.DIEMTHI) AS DIEM_TRUNG_BINH
FROM SINHVIEN
JOIN DIEM ON SINHVIEN.MASV = DIEM.MASV
JOIN MONHOC ON DIEM.MAMH = MONHOC.MAMH
WHERE DIEM.LANTHI = (SELECT MAX(LANTHI) 
                    FROM DIEM
                    WHERE MAMH = MONHOC.MAMH AND MASV = SINHVIEN.MASV)
GROUP BY SINHVIEN.MASV, SINHVIEN.HOTEN
HAVING AVG(DIEM.DIEMTHI) = (
  SELECT MAX(AVG_DIEMTRUNG_BINH)
  FROM (
    SELECT AVG(DIEM.DIEMTHI) AS AVG_DIEMTRUNG_BINH
    FROM SINHVIEN
    JOIN DIEM ON SINHVIEN.MASV = DIEM.MASV
    JOIN MONHOC ON DIEM.MAMH = MONHOC.MAMH
    WHERE DIEM.LANTHI = (SELECT MAX(LANTHI) 
                          FROM DIEM
                          WHERE MAMH = MONHOC.MAMH AND MASV = SINHVIEN.MASV)
    GROUP BY SINHVIEN.MASV
  ) AS TEMP
);
